### ISSUE TITLE
US01-01 : Accès à une barre de navigation

### ISSUE THREAD

**Issue by Nini1551** [Nini1551/RoleMaster#3]
[US01-01 : Accès à une barre de navigation](https://github.com/Nini1551/RoleMaster/wiki/Epic-Us-Backlog#us01-01--acc%C3%A8s-%C3%A0-une-barre-de-navigation)
* Ecrire une en-tête au pattern par défaut d'une page (header)
* A gauche, utiliser par défaut un logo comme bouton afin de rediriger vers la page s'accueil ("home")
* A droite, écrire un bouton "S'inscrire" pour rediriger vers la page d'inscription ("register").
* A droite, écrire un bouton "Se connecter" pour rediriger vers la page de connexion ("login").

**Comment by Nini1551** [comment]
Voici ce qui reste, pour moi à faire sur cette issue : 
* Revoir le logo (j'ai pris un logo libre de droit aléatoire).
* Changer le look de la navbar (voir CSS)
* (FACULTATIF) Retravailler le footer

**Comment by Insanytil** [comment]
### Valide :
- L'accès aux pages Home, Register, Login est fonctionnel.
- La Navbar (header) et le footer sont présent sur chaque page.
- Les boutons de la navbar sont fonctionnels et redirigent bien vers leur page respective 


### A revoir : 
- Le style et la mise en page de la Navbar
- Footer : très sobre cependant est-ce nécessaire de rajouter des informations supplémentaires ?

**Comment by Insanytil** [comment]
* Modification du style de la navbar
* ajout du logo sur la navbar et sur l'icon

**Comment by Nini1551** [comment]
* Accorder le CSS du bas de page avec celui de la barre de navigation

**Comment by Insanytil** [comment]
* mise à jour de la responsivness du site ( taille <  770X808) suppression du titre et centralisation du logo et des boutons
* Mise à jour des règles css du footer
