### ISSUE TITLE
US01-04 : Accès à une page de gestion de profil

### ISSUE THREAD

**Issue by Nini1551** [Nini1551/RoleMaster#7]
[US01-04 : Accès à une page de gestion de profil](https://github.com/Nini1551/RoleMaster/wiki/Epic-Us-Backlog#us01-04--acc%C3%A8s-%C3%A0-une-page-de-gestion-de-profil)
* Créer une page de profil s'adaptant à chaque utilisateur ("user/ID")
* Ecrire une requête GET ("user/ID") afin de récupérer les données suivantes de l'utilisateur : 
  * son pseudonyme
  * son adresse e-mail
  * son mot de passe
  * sa date de création
* Afficher les différentes données de l'utilisateur précédées par sa photo de profil (photo de profil par défaut si il n'en a pas). A la place du mot de passe, afficher "**********"
* A la suite du mot de passe, écrire un bouton "Modifier" qui permet la modification de son mot de passe (uniquement si il s'agit de son propre compte).
* Si l'utilisateur modifie son mot de passe, créer un formulaire à la place de l'affichage du mot de passe avec les champs suivants : 
  * son nouveau mot de passe (caché)
  * une confirmation de son nouveau mot de passe (caché)
* Vérifier si le mot de passe est valide : au minimum 8 caractères dont une lettre minuscule, une lettre majuscule, un chiffre et un caractère spécial
* Vérifier si la confirmation du mot de passe concorde avec le mot de passe.
* Si un champ n'est pas valide, signale le manquement après que l'utilisateur rentre la donnée.
* Ecrire une requête PUT ("change_password/ID") afin de modifier le mot de passe entré préalablement crypté via la fonction de hachage SHA-256.
* Le changement de mot de passe fait, recharger la page.
* Ajouter la photo de profil de l'utilisateur à gauche du bouton de déconnexion de la barre de navigation qui, quand cliqué, amène vers la page de profil de l'utilisateur ("user/ID")

**Comment by Insanytil** [comment]
# OK 
- Les données sont récupérées correctement (sauf la date de création)
- les données sont affichées correctement ![image](https://github.com/user-attachments/assets/c8233536-7592-4ccc-b536-b4eaccee21fc)
- les boutons modifiées sont fonctionnels 
**username**
![image](https://github.com/user-attachments/assets/beb0d28d-3739-49e1-8854-f2e653b0faed)
**email**
![image](https://github.com/user-attachments/assets/7fe149f7-f556-41ce-a27f-706967c28000)
**mdp**
![image](https://github.com/user-attachments/assets/5fdbd95b-c8fd-4465-8572-a00767406b91)

* Requête de changement de mot de passe, username, email fonctionnels

# PAS OK 
- Photo de profil pas opérationnelle
- vérification des données dans les champs des différents forms non opérationnelle
